const data = {
  products: [
    {
      _id: '1',
      img:"/assets/p65.png",
      title: "Logitech Jaybird Wireless-Bluetooth-Earbuds",
      desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quas debitis quis vero similique.",
      category: "Earbuds",
      price: 5000,
      rating: 4.5,
      countInStock: 10,
    },
    {
      _id: '2',
      img:"/assets/p63.png",
      title: "Sony SRS-XB13 Compact_&_Portable Waterproof-Wireless-Bluetooth",
      desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quas debitis quis vero similique.",
      category: "Speakers",
      price: 1090,
      rating: 3.5,
      countInStock: 10,
    },
    {
      _id: '3',
      img:"/assets/p50.png",
      title: "RealmeX20pro",
      desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quas debitis quis vero similique.",
      category: "Phones",
      price: 15000,
      rating: 2.99,
      countInStock: 10,
    },
    {
      _id: '4',
      img:"/assets/p27.png",
      title: "Microsoft Modern USB-C Speaker",
      desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quas debitis quis vero similique.",
      category: "Speakers",
      price: 10000,
      rating: 3.5,
      countInStock: 10,
    },
    {
      _id: '5',
      img:"/assets/p64.png",
      title: "Sony-High Power XB60 Bluetooth Speaker",
      desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quas debitis quis vero similique.",
      category: "Speakers",
      price: 10000,
      rating: 3.8,
      countInStock: 0,
    },
    {
      _id: '6',
      img:"/assets/p10.png",
      title: "Sentry Bluetooth Sport wireless",
      desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quas debitis quis vero similique.",
      category: "Hearpods",
      price: 8700,
      rating: 3.9,
      countInStock: 10,
    },
    {
      _id: '7',
      img:"/assets/p1.png",
      title: "Mugo Wireless Earbuds Bluetooth Earbuds",
      desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quas debitis quis vero similique.",
      category: "Earbuds",
      price: 8780,
      rating: 3.5,
      countInStock: 10,
    },
    {
      _id: '8',
      img:"/assets/p62.png",
      title: "Black M2 Smart Fitness Watch For Gym",
      desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quas debitis quis vero similique.",
      category: "Watches",
      price: 8700,
      rating: 3.5,
      countInStock: 10,
    },
    {
      _id: '9',
      img:"/assets/p25.png",
      title: "JBL Link Music | Wi-Fi Speaker",
      desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quas debitis quis vero similique.",
      category: "Speakers",
      price: 8700,
      rating: 4.0,
      countInStock: 10,
    },
    {
      _id: '10',
      img:"/assets/p66.png",
      title: "SoundRover Wireless Party Speaker",
      desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quas debitis quis vero similique.",
      category: "Speakers",
      price: 8700,
      rating: 4.1,
      countInStock: 10,
    },
    {
      _id: '11',
      img:"/assets/p29.png",
      title: "JBL Buds Air Sport Wireless Bluetooth Earbuds",
      desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quas debitis quis vero similique.",
      category: "Earbuds",
      price: 87.00,
      rating: 4.2,
      countInStock: 10,
    },
    {
      _id: '12',
      img:"/assets/p2.png",
      title: "Microsoft New Intelligent Speaker",
      desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quas debitis quis vero similique.",
      category: "Speakers",
      price: 87.00,
      rating: 4.0,
      countInStock: 10,
    },
    // {
    //   _id: '13',
    //   img:"../src/assets/p44.png",
    //   title: "JBL Wired Headphone",
    //   desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quas debitis quis vero similique.",
    //   category: "Headphones",
    //   price: 87.00,
    //   rating: 3.0,
    //   countInStock: 10,
    // },
    // {
    //   _id: '14',
    //   img:"../src/assets/p4.png",
    //   title: "CelesTech Wireless Charging Stand With Speaker",
    //   desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quas debitis quis vero similique.",
    //   category: "Speakers",
    //   price: 87.00,
    //   rating: 4.6,
    //   countInStock: 10,
    // },
    // {
    //   _id: '15',
    //   img:"../src/assets/p20.png",
    //   title: "Amazon In Ear Bluetooth Earbuds",
    //   desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quas debitis quis vero similique.",
    //   category: "Earbuds",
    //   price: 87.00,
    //   rating: 4.45,
    //   countInStock: 10,
    // },
    // {
    //   _id: '16',
    //   img:"../src/assets/p11.png",
    //   title: "Meridian Wireless Bluetooth Earbuds",
    //   desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quas debitis quis vero similique.",
    //   category: "Earbuds",
    //   price: 87.00,
    //   rating: 4.9,
    //   countInStock: 10,
    // },
    // {
    //   _id: '17',
    //   img:"../src/assets/oppoF17.png",
    //   title: "OPPO Find17",
    //   desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quas debitis quis vero similique.",
    //   category: "Phones",
    //   price: 87.00,
    //   rating: 4.8,
    //   countInStock: 10,
    // },
    // {
    //   _id: '18',
    //   img:"../src/assets/oppofindX2.png",
    //   title: "OPPO FindX2",
    //   desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quas debitis quis vero similique.",
    //   category: "Phones",
    //   price: 87.00,
    //   rating: 4.5,
    //   countInStock: 10,
    // },
    // {
    //   _id: '19',
    //   img:"../src/assets/p6.png",
    //   title: "Sentry Air Sport Wireless Earbuds",
    //   desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quas debitis quis vero similique.",
    //   category: "Earbuds",
    //   price: 87.00,
    //   rating: 4.3,
    //   countInStock: 10,
    // },
    // {
    //   _id: '20',
    //   img:"../src/assets/p68.png",
    //   title: "Samsung Galaxy S21 5G Smartphone",
    //   desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quas debitis quis vero similique.",
    //   category: "Phones",
    //   price: 87.00,
    //   rating: 4.1,
    //   countInStock: 10,
    // },
    // {
    //   _id: '21',
    //   img:"../src/assets/samsGalaxyNote20.png",
    //   title: "Samsung Galaxy Note20",
    //   desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quas debitis quis vero similique.",
    //   category: "Phones",
    //   price: 87.00,
    //   rating: 4.0,
    //   countInStock: 10,
    // },
  ]
};

module.exports = { data };